### ISSUE TITLE
Restreamer: Custom transitions throw an internal server error

### ISSUE THREAD

**Issue by dcollinsn** [dbvideostriketeam/wubloader#470]
When attempting to use MPEG-TS mode to download a multi-range edit using a custom transition, I get the following error from restreamer:

```
restreamer_1        | [2024-11-09 00:45:00,975]     INFO root(segments:621): Running ffmpeg with args: ffmpeg -hide_banner -loglevel error -ss 1.234 -t 48.198 -i /proc/self/fd/8 -ss 1.093 -t 90.743 -i /proc/self/fd/10 -filter_complex [0:v][1:v]xfade=duration=1.0:offset=47.198:transition=custom:expr='('A 360 degree clockwise sweep around the center of the screen, starting at the top.\nIntended to mimic an analog clock and insinuate a passing of time.', 'if(lt((1-atan2(W/2-X,Y-H/2)/PI) / 2, P), A, B)')'[v0]; [0:a][1:a]acrossfade=duration=1.0[a0] -map [v0] -map [a0] -c:v libx264 -preset ultrafast -crf 0 -f mpegts -
restreamer_1        | [AVFilterGraph @ 0x71e181c3fd40] No such filter: 'starting at the top.nIntended to mimic an analog clock and insinuate a passing of time., if(lt((1-atan2(W/2-X'
restreamer_1        | Error initializing complex filters.
restreamer_1        | Invalid argument
restreamer_1        | Traceback (most recent call last):
restreamer_1        |   File "/usr/lib/python3.9/site-packages/gevent/pywsgi.py", line 999, in handle_one_response
restreamer_1        |     self.run_application()
restreamer_1        |   File "/usr/lib/python3.9/site-packages/gevent/pywsgi.py", line 946, in run_application
restreamer_1        |     self.process_result()
restreamer_1        |   File "/usr/lib/python3.9/site-packages/gevent/pywsgi.py", line 930, in process_result
restreamer_1        |     for data in self.result:
restreamer_1        |   File "/usr/lib/python3.9/site-packages/werkzeug/wsgi.py", line 256, in __next__
restreamer_1        |     return self._next()
restreamer_1        |   File "/usr/lib/python3.9/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
restreamer_1        |     for item in iterable:
restreamer_1        |   File "/usr/lib/python3.9/site-packages/common/segments.py", line 1022, in full_cut_segments
restreamer_1        |     yield chunk
restreamer_1        |   File "/usr/lib/python3.9/contextlib.py", line 126, in __exit__
restreamer_1        |     next(self.gen)
restreamer_1        |   File "/usr/lib/python3.9/site-packages/common/segments.py", line 637, in ffmpeg_cut_many
restreamer_1        |     raise Exception("Error while cutting: ffmpeg exited {}".format(ffmpeg.returncode))
restreamer_1        | Exception: Error while cutting: ffmpeg exited 1
restreamer_1        | 2024-11-09T00:45:01Z {'REMOTE_ADDR': '172.18.0.7', 'REMOTE_PORT': '57748', 'HTTP_HOST': 'restreamer:8000', (hidden keys: 32)} failed with Exception
restreamer_1        |
restreamer_1        | 172.18.0.7 - - [2024-11-09 00:45:01] "GET /cut/desertbus/source.ts?type=mpegts&allow_holes=false&range=2024-11-09T00%3A24%3A17.327%2C2024-11-09T00%3A25%3A05.525&range=2024-11-09T00%3A27%3A43.186%2C2024-11-09T00%3A29%3A13.929&transition=clockwipe%2C1 HTTP/1.0" 500 161 0.173045
```

**Comment by dcollinsn** [comment]
https://github.com/dbvideostriketeam/wubloader/commit/2fcbff3b44559ef783edeb4b8fe7a2b571d8407d
